sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CODE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in ud-docker-course-fib-calc-gcp-svc-acct.json.enc -out ud-docker-course-fib-calc-gcp-svc-acct.json -d
  - echo "about to execute curl" 
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - echo "about to execute source"
  - source $HOME/google-cloud-sdk/path.bash.inc
  - echo "about to execute first gcloud"
  - gcloud components update kubectl
  - echo "about to execut auth"
  - gcloud auth activate-service-account --key-file ud-docker-course-fib-calc-gcp-svc-acct.json
  - gcloud config set project multi-k8s-220001
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials fib-calc-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t dc13ml/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dc13ml/react-test npm test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
